platform :ios,'8.0'
use_frameworks!

target 'kaidexing' do
    pod "ReactiveCocoa", "~>2.0.0"
    pod "AFNetworking", "~> 3.0"
    
    pod 'JSONModel'
    pod 'ActionSheetPicker-3.0', '~> 1.3.4'
    pod 'Mixpanel'
    pod 'Pingpp'
    pod 'CocoaLumberjack'
    pod 'Bugly'
   pod 'CAMagicProximityKit'
   pod  'JPush'
end

